development:
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  database: insultario_development

test:
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  database: insultario_test

production:
  url: <%= ENV['DATABASE_URL'] %>
